[package]
name = "task_manager"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.128", features = ["derive"] }
serde_json = "1.0.117"# Versão alterada para 1.0.117 pois o compilador acusa a inexistencia ou não publicação da versão 1.0.210